project_id = "hlydtwqhiuwbikkjemck"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.login-by-username]
verify_jwt = false

[functions.auth-token]
verify_jwt = false

[functions.test-auth]
verify_jwt = false

[functions.test-admin-login]
verify_jwt = false

[functions.get-paginated-users]
verify_jwt = false

[functions.get-paginated-transactions]
verify_jwt = false

[functions.deposit-game-api]
verify_jwt = false

[functions.withdraw-game-api]
verify_jwt = false

[functions.user-register]
verify_jwt = false

[functions.get-games-list]
verify_jwt = false

[functions.get-games-from-database]
verify_jwt = false

[functions.sync-games-database]
verify_jwt = false

[functions.game-login]
verify_jwt = false

[functions.register-player]
verify_jwt = false

[functions.check-username]
verify_jwt = false

[functions.create-deposit-order]
verify_jwt = true

[functions.payos-webhook]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"

[studio]
enabled = true
port = 54323
api_url = "https://api.dinamondbet68.com"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
site_url = "https://dinamondbet68.com/"
additional_redirect_urls = ["https://dinamondbet68.com/", "https://www.dinamondbet68.com/"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
