// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Local Supabase configuration
const LOCAL_SUPABASE_URL = import.meta.env.VITE_LOCAL_SUPABASE_URL || "http://206.206.126.141:54321";
const LOCAL_SUPABASE_ANON_KEY = import.meta.env.VITE_LOCAL_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Cloud Supabase configuration (fallback)
const CLOUD_SUPABASE_URL = import.meta.env.VITE_CLOUD_SUPABASE_URL || "https://hlydtwqhiuwbikkjemck.supabase.co";
const CLOUD_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_CLOUD_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhseWR0d3FoaXV3Ymlra2plbWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTA1MjQsImV4cCI6MjA2OTgyNjUyNH0.deIb21DJNmyM5ZjocFAl4j_47AF6CnY26LN0Bn9eB9k";

// Force use local database
const SUPABASE_URL = LOCAL_SUPABASE_URL;
const SUPABASE_ANON_KEY = LOCAL_SUPABASE_ANON_KEY;

console.log('Using Supabase: LOCAL');
console.log(`Supabase URL: ${SUPABASE_URL}`);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});